### ISSUE TITLE
MongoDB Expcetion on Startup

### ISSUE THREAD

**Issue by ghost** [Beastw00d/backgroundServiceExample#2]
Hello,

Maybe you could add [Microsoft.EntityFrameworkCore.InMemory](https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.InMemory) instead of a real db. Thanks for the awesome sample. Learned a lot :-)

best
Eric

**Comment by Beastw00d** [comment]
@ericbrunner that's a great idea. Ill start working on that. I'm glad it helped!

**Comment by Beastw00d** [comment]
@ericbrunner hey so I wasn't able to get in memory sql working with platibus (the event framework) BUT i did get it to work with in memory mongo using mongo2go. Could you pull the most recent master and let me know if this resolves your issues?

Here is the commit to add mongo2go: https://github.com/Beastw00d/backgroundServiceExample/commit/7a31e13b20143e70cb972d7aeda84a210a25d990

**Comment by ghost** [comment]
@Beastw00d Thanks for fixing that. Now your sample works out of the box.
