### ISSUE TITLE
How-to: ExecuteAsync Exception Handling (Restart ?) vs. Azure Function

### ISSUE THREAD

**Issue by ghost** [Beastw00d/backgroundServiceExample#3]
Hi

Currently I wonder how to restart a BackgroundService in case of some runtime
exception. Is there any possible way? 

I read a lot the last week(s) and an Azure Function that does such background work
seems to be more suitable because that runs again (e.g. a Timer Function) even in case 
of an exception in the function itself.

Thanks for any hint.
Best
Eric

**Comment by Beastw00d** [comment]
@ericbrunner I'd recommend either wrapping a try catch around the service method that the background service is calling or in the background service.
```csharp
// --- example one ----
// JournalingManagerService.cs
protected override async Task ExecuteAsync(CancellationToken stoppingToken)
{
    while (!stoppingToken.IsCancellationRequested)
    {
                
        await _journalingUpdateService.Update(stoppingToken);
        await Task.Delay(CheckUpdateTime, stoppingToken);
    }

    await Task.CompletedTask;
}

// JournalingUpdateService.cs
public async Task Update(CancellationToken cancellationToken)
{
    try { ... }
    catch (Exception ex)  {...}
}
```
```csharp
// --- example two ---
// JournalingManagerService.cs
protected override async Task ExecuteAsync(CancellationToken stoppingToken)
{
    while (!stoppingToken.IsCancellationRequested)
    {
        try
        {        
            await _journalingUpdateService.Update(stoppingToken);
        }
        catch (Exception ex) {...}
        await Task.Delay(CheckUpdateTime, stoppingToken);
    }

    await Task.CompletedTask;
}
```

The goal would be to only have the background service to stop when the application stops, known as graceful. Another thing that might help is logging when the background service is stopping ungracefully which can be done by the following code.
```csharp
// BackgroundService.cs
public virtual Task StartAsync(CancellationToken cancellationToken)
{
    // Store the task we're executing
    _executingTask = ExecuteAsync(_stoppingCts.Token);

    // If the task is completed then return it, this will bubble cancellation and failure to the caller
    if (_executingTask.IsCompleted)
    {
        _logger.Log("Background service has stopped ...");
        return _executingTask;
    }

    // Otherwise it's running
    return Task.CompletedTask;
}
```

Hope this helped. Let me know if I missed anything or if you have any questions?

Thanks,
Chris

**Comment by ghost** [comment]
@Beastw00d Thanks Chris. Will do that `try-catch`-ing in `ExecuteAsync `and log that execption to `Application Insights` and send me an email to be notified to restart the whole Api App. I guess in such case there is no other way than restart the whole Api App to get the BackgroundService properly restarted. I have to observe and decide whats best. The narrowed down `try-catch`-ing  in the repository methods is in my mind , too. Have to collect some experience with that in **netcore21**. If it doesn't properly work , [Azure Function Timer](https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-scheduled-function) is a good first class citizen solution.
